### ISSUE TITLE
overlapping of icons 

### ISSUE THREAD

**Issue by nibivid** [spyder-ide/spyder-reports#86]
![image](https://user-images.githubusercontent.com/25265126/118141080-9ff01380-b426-11eb-8332-c9030c9d3495.png)

First of all: Thanks a lot for making such a great application, am just loving it . I hope the community is open to some recommendations and improvements. 

Version details :
* Spyder version: 5.0.0 None
* Python version: 3.9.4 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

Issue :
overlapping of icons 

Screen short:
![image](https://user-images.githubusercontent.com/25265126/118141368-ea719000-b426-11eb-8ce0-4f8aed7d456c.png)

Description :
As you can see from the scene short the icons are overlapping on the text in the menu. Am using a feel xps15 which has a high dpi display, so the auto high dpi setting is enabled. Am not sure what is causing this issue it would be great if you put some time into looking into this. 

thanks 
-Nibin

**Comment by ccordoba12** [comment]
Hey @nibivid, thanks for reporting. This is an error in Spyder (not in the package on this repository) and it was fixed in our 5.0.1 version, released several weeks ago. Unfortunately, it's not part of Anaconda yet, but hopefully it will be soon.

Also, for next time, please report Spyder errors here:

https://github.com/spyder-ide/spyder/issues
